### ISSUE TITLE
error on using curl

### ISSUE THREAD

**Issue by pentest01** [G4lB1t/pstf2#2]
i get this error, if i access the url using curl with this command curl -A "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" http://localhost -v

Exception occurred during processing of request from ('127.0.0.1', 33894)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 420, in handle_one_request
    method()
  File "/home/kali/pstf2/lib/servers/http_server.py", line 45, in do_GET
    is_blacklisted = fp.do_checks(headers_to_check)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pstf2/lib/fingerprinting/blacklist_checks.py", line 55, in do_checks
    p0f_data = get_p0f_data(client_ip)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/pstf2/lib/servers/p0f_wrapper.py", line 40, in get_p0f_data
    data = p0f.get_info(ip)
           ^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/p0f/__init__.py", line 124, in get_info
    self.client.send(data_send)
    ^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/p0f/__init__.py", line 94, in client
    self._client.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by G4LB1T** [comment]
From the output it seems like you are not running it as a Docker image - this might lead to annoying versioning-related issues (I guess it has something to do with Python and/or its modules).
My advice is to run it as a Docker image to avoid getting these errors.
